---

# Main tasks file for virtualenv role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::virtualenv'
    - 'role::virtualenv::init'
    - 'role::virtualenv::install'


- name: 'INSTALL | Manage packages installation'
  become: True
  package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ virtualenv_packages }}"
  tags:
    - 'role::virtualenv'
    - 'role::virtualenv::install'
