---

# Main tasks file for virtualenv role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::virtualenv'
    - 'role::virtualenv::init'


- name: Load OS variables
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yml"
  tags:
    - virtualenv
    - install

- name: Install packages
  become: True
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ virtualenv_packages }}"
  tags:
    - virtualenv
    - install

